name: Build and Deploy images

env:
  NODE_VERSION : '22.8.0'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
    - run: npm install
    - run: npm run build --prod

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Define tags
      id: vars
      run: |
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)
        DATE_TAG=$(date +"%Y%m%d%H%M")
        echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        echo "IMAGE_TAG=v${DATE_TAG}-${SHORT_SHA}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }} .
        docker tag ghcr.io/${{ github.repository_owner  }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest


